### ISSUE TITLE
Unable to "install networking"

### ISSUE THREAD

**Issue by romanost** [OriHoch/kamatera-k8s#1]
No bind on port 8080 after installing by the manual and getting error running the "Install networking" commands.

```
root@kb:~# kubectl apply -f https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/rbac.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@kb:~# kubectl apply -f https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/canal.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@kb:~#
```

**Comment by OriHoch** [comment]
thanks @romanost  
I updated the README, you need to run `export KUBECONFIG=/etc/kubernetes/admin.conf` to be able to run `kubectl` commands on the master node

**Comment by OriHoch** [comment]
@romanost published a new release - https://github.com/OriHoch/kamatera-k8s/releases/tag/v0.0.2

**Comment by romanost** [comment]
The EXPORT command is per session, you need to add it permanent .
cat "KUBECONFIG=/etc/kubernetes/admin.conf" >> /etc/environment

**Comment by OriHoch** [comment]
thanks @romanost opened issue - #3
