### ISSUE TITLE
[question] how should users manage their DNS?

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/kamatera-k8s#16]
possible options - 
* manually - get the traefik node external IP, set DNS A record to that IP
* automatically - users provide credentials for DNS API and we add / modify DNS records for them

see the [list of traefik supported DNS apis](https://docs.traefik.io/configuration/acme/#dnsprovider) - it should be easy to support any one from this list. It also be used to issue SSL certificates.

[Cloudflare](https://www.cloudflare.com/) is a very good option IMO - both for the DNS API and also for the protection and caching features.

**Comment by OriHoch** [comment]
@yohaya

**Comment by yohaya** [comment]
manually, we just need to show them exactly what is the wan ip address of the system.

**Comment by OriHoch** [comment]
fixed in [v0.0.4](https://github.com/OriHoch/kamatera-k8s/releases) - 
kamatera `cluster lb info` command outputs the load balancer external IP

see the updated [README](https://github.com/OriHoch/kamatera-k8s/blob/master/README.md#installing-a-load-balancer-to-allow-secure-external-access-to-the-cluster)
