### ISSUE TITLE
Disable swap

### ISSUE THREAD

**Issue by romanost** [OriHoch/kamatera-k8s#2]
swapoff -a disables the swap but it turn on after a reboot
The swap should be removed from /etc/fstab

**Comment by OriHoch** [comment]
generally, I think I would prefer to use blue/green type deployment where we only create new nodes - no need to reboot
but of course, it's easy to add this to /etc/fstab if you need that

**Comment by yohaya** [comment]
It will be great to have it in the fstab, as vms/nodes might restarted for many reasons (even OS kernel update), so the configuration should set this permanently.

**Comment by OriHoch** [comment]
fixed in [v0.0.5](https://github.com/OriHoch/kamatera-k8s/releases)
